sudo: required
node_js: false
script:
  - nvm install v7.1
  - node --version
  - npm install webdriverio
  - npm install wdio-junit-reporter
  - npm install wdio-spec-reporter
  - npm install wdio-mocha-framework
  - npm install wdio-sauce-service --save-dev
  - npm install wdio-allure-reporter --save-dev
  - npm install -g allure-commandline --save-dev
  - ./node_modules/.bin/wdio wdio.conf.js
  - allure generate allure-results
  - ls ./allure-results
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: allure-results
  on:
    branch: master
