language: node_js
sudo: required
node_js:
  - "7.1"
addons:
  sauce_connect: true
script:
  #- nvm install v7.1
  #- node --version
  - npm install webdriverio 
  #- npm install wdio-junit-reporter 
  - npm install wdio-spec-reporter 
  - npm install wdio-mocha-framework 
  - npm install wdio-sauce-service 
  - npm install wdio-allure-reporter 
  - npm install -g allure-commandline 
  #- dig saucelabs.com
  - ./node_modules/.bin/wdio wdio.conf.js
  - cat ./sc.log
  - ls -l
  - allure generate allure-report
  - ls -l
  - ls ./allure-report
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#  local_dir: allure-report
#  on:
#    branch: master
