language: node_js
dist: precise
sudo: false
node_js:
  - stable
  - 7
script:
  #- nvm install v7.1
  #- node --version
  - npm install webdriverio --save-dev
  #- npm install wdio-junit-reporter --save-dev
  - npm install wdio-spec-reporter --save-dev
  - npm install wdio-mocha-framework --save-dev
  - npm install wdio-sauce-service --save-dev
  - npm install wdio-allure-reporter --save-dev
  - npm install -g allure-commandline --save-dev
  #- dig saucelabs.com
  - ./node_modules/.bin/wdio wdio.conf.js
  - ls -l
  - allure generate allure-report
  - ls -l
  - ls ./allure-report
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
#  local_dir: allure-report
#  on:
#    branch: master
